"""Agentic tool-use episodes: the third training stage.

The step up from GRPO is that the model no longer answers in one shot -- it may
call a tool, see real output, and revise. That is the whole point (a coding agent
is defined by its loop), and it is also where the sharp edges are:

  * AN UNPARSEABLE REPLY IS A FINAL ANSWER, NOT A CRASH. Early in training the
    policy emits malformed tool calls constantly. Raising on them would mean the
    episodes that fail are exactly the ones that never produce a gradient, so
    the model would be trained only on the behaviour it already has.
  * EVERY EPISODE TERMINATES. A hard turn limit, and tool output truncated to a
    budget, because a tool that returns a megabyte of traceback otherwise fills
    the context and every later turn is spent re-reading it.
  * TOOL OUTPUT IS UNTRUSTED TEXT. It is generated by code the policy wrote, so
    it is inserted as a TOOL turn's content and never interpreted as protocol.

The call convention is a fenced ```tool block containing JSON. JSON because it
is unambiguous to parse and the model has seen a great deal of it in pretraining;
a fence because the model has seen a great deal of those too.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field

from nanocoder.chat import ASSISTANT, SYSTEM, TOOL, USER, tokenize_prompt
from nanocoder.sandbox import run_python, run_tests

TOOL_FENCE = re.compile(r"```tool\s*\n(.*?)(?:```|\Z)", re.DOTALL)

AGENT_SYSTEM = (
    "You are a coding agent. You may call a tool by emitting a fenced block:\n"
    "```tool\n{\"name\": \"run_python\", \"args\": {\"code\": \"print(1)\"}}\n```\n"
    "Tools: run_python(code) runs Python and returns its output; "
    "run_tests(code) runs your code against the task's hidden tests and reports "
    "how many passed. You do not write the tests and cannot see them.\n"
    "When the tests pass, reply with your final answer as a ```python block."
)

# THE TASK'S TESTS ARE SUPPLIED BY THE HARNESS, NEVER BY THE MODEL. Letting the
# model pass its own `tests` was a real and costly mistake: the SFT trajectories
# contained them, so the policy learned to GENERATE them, and generated broken
# ones. `def identity(x): return x` -- correct code -- scored 0/3 against its own
# hallucinated `assert identity(9) is x`. The policy was graded on its invented
# grader rather than its code, every episode scored 0, every group was
# zero-variance, and the stage produced zero updates.

MAX_TOOL_CHARS = 1200
ERR_PREFIX = "error: "


@dataclass
class TurnRecord:
    """One assistant turn, kept as TOKEN IDS rather than text.

    The RL update needs log-probs of the tokens that were actually sampled.
    Recovering them by decoding the turn to text and re-encoding it is not safe:
    BPE decode->encode is not guaranteed to round-trip, so the log-probs would be
    scored against a slightly different token sequence than the one that was
    generated -- misaligning them from the sampled `logprobs` the ratio compares
    against, silently and only on some turns.
    """
    prompt_ids: list
    tokens: object            # LongTensor [1, L]
    valid: object             # BoolTensor [1, L]
    logprobs: object          # FloatTensor [1, L] or None


@dataclass
class Episode:
    messages: list
    turns: int = 0
    tool_calls: int = 0
    tool_errors: int = 0
    final: str = ""
    transcript: list = field(default_factory=list)
    steps: list = field(default_factory=list)      # TurnRecord per assistant turn
    final_from_tool_call: bool = False             # answer recovered from a tool call


def parse_tool_call(text: str):
    """Returns (name, args) or None if this is not a well-formed tool call."""
    m = TOOL_FENCE.search(text)
    if not m:
        return None
    try:
        payload = json.loads(m.group(1).strip())
    except (json.JSONDecodeError, ValueError):
        return None
    # Valid JSON is not necessarily an OBJECT: a bare list, string or number
    # parses fine and then has no .get, which raised AttributeError and killed
    # the episode -- exactly the "never raise on model output" promise above.
    if not isinstance(payload, dict):
        return None
    name, args = payload.get("name"), payload.get("args", {})
    if not isinstance(name, str) or not isinstance(args, dict):
        return None
    return name, args


def _has_code(text: str) -> bool:
    from nanocoder.reward import extract_code
    return bool(extract_code(text or ""))


def _truncate(s: str) -> str:
    s = s or ""
    if len(s) <= MAX_TOOL_CHARS:
        return s
    half = MAX_TOOL_CHARS // 2
    return s[:half] + f"\n...[{len(s) - MAX_TOOL_CHARS} chars elided]...\n" + s[-half:]


class ToolBox:
    """The three tools, each returning a plain string for the TOOL turn.

    `read_file` is scoped to one directory and resolves symlinks before checking
    containment -- `os.path.normpath` alone would accept a symlink pointing out
    of the sandbox, which is the standard way this check is written wrong.
    """

    def __init__(self, scratch_dir: str | None = None, timeout: float = 6.0,
                 tests: list[str] | None = None, setup: str = ""):
        self.scratch = os.path.realpath(scratch_dir) if scratch_dir else None
        self.timeout = timeout
        self.tests = list(tests or [])
        self.setup = setup

    def for_task(self, task):
        """Point this toolbox at one task's hidden tests, for one episode."""
        self.tests = list(task.tests)
        self.setup = getattr(task, "setup", "")
        return self

    def run_python(self, code: str = "", **_):
        if not isinstance(code, str) or not code.strip():
            return f"{ERR_PREFIX}run_python needs a non-empty 'code' string"
        r = run_python(code, timeout=self.timeout)
        if r.timed_out:
            return f"error: timed out after {self.timeout}s"
        return _truncate((r.stdout + ("\n" + r.stderr if r.stderr else "")).strip()) or "(no output)"

    def run_tests(self, code: str = "", **kw):
        """Run the model's code against the HARNESS-supplied hidden tests.

        Any `tests` the model passes are ignored on purpose -- see the note by
        AGENT_SYSTEM. Accepting them taught the policy to invent its own grader.
        """
        if not isinstance(code, str) or not code.strip():
            return f"{ERR_PREFIX}run_tests needs a non-empty 'code' string"
        if not self.tests:
            return f"{ERR_PREFIX}no tests are configured for this task"
        passed, total, detail = run_tests(code, self.tests, timeout=self.timeout,
                                          setup=self.setup)
        note = "\n(note: the tests are fixed by the task; yours were ignored)" if "tests" in kw else ""
        return _truncate(f"{passed}/{total} tests passed"
                         + (f"\n{detail}" if detail else "") + note)

    def read_file(self, path: str = "", **_):
        if self.scratch is None:
            return "error: no scratch directory is configured"
        target = os.path.realpath(os.path.join(self.scratch, path))
        if not (target == self.scratch or target.startswith(self.scratch + os.sep)):
            return "error: path escapes the scratch directory"
        if not os.path.isfile(target):
            return f"error: no such file: {path}"
        with open(target, encoding="utf-8", errors="replace") as fh:
            return _truncate(fh.read())

    def dispatch(self, name: str, args: dict) -> tuple[str, bool]:
        """Returns (output_text, ok).

        `ok` reports whether the call actually WORKED, not merely whether
        dispatch avoided an exception -- a tool that rejects its arguments and
        returns an error string is an error from the agent's point of view, and
        counting it as a success made `tool_errors` silently undercount the
        thing it exists to measure. The signal is the ERR_PREFIX convention, so
        a tool whose genuine stdout happens to start with "error: " is
        misattributed in that DIAGNOSTIC counter only; nothing in the reward or
        the update depends on it.
        """
        fn = {"run_python": self.run_python, "run_tests": self.run_tests,
              "read_file": self.read_file}.get(name)
        if fn is None:
            return f"{ERR_PREFIX}unknown tool {name!r}", False
        try:
            out = fn(**args)
        except TypeError as e:
            return f"{ERR_PREFIX}bad arguments for {name}: {e}", False
        except Exception as e:                    # a tool must never kill the episode
            return f"{ERR_PREFIX}{type(e).__name__}: {e}", False
        return out, not str(out).startswith(ERR_PREFIX)


def run_episode(model, tok, question: str, toolbox: ToolBox, eos_id: int,
                max_turns: int = 4, max_new_tokens: int = 256,
                temperature: float = 1.0, n_loops: int | None = None,
                record_logprobs: bool = False) -> Episode:
    """One multi-turn rollout. Always returns; never raises on model output.

    `record_logprobs=True` is for RL and forces on-policy sampling (temperature
    1.0, untruncated) because `generate` refuses to return log-probs from a
    modified distribution -- see generate() for why that matters.
    """
    from nanocoder.generate import generate

    ep = Episode(messages=[{"role": SYSTEM, "content": AGENT_SYSTEM},
                           {"role": USER, "content": question}])
    for _ in range(max_turns):
        prompt_ids = tokenize_prompt(tok, ep.messages)
        toks, valid, lp = generate(
            model, prompt_ids, max_new_tokens=max_new_tokens, eos_id=eos_id,
            temperature=1.0 if record_logprobs else temperature,
            num_return_sequences=1, n_loops=n_loops, return_logprobs=record_logprobs,
        )
        ep.steps.append(TurnRecord(prompt_ids=prompt_ids, tokens=toks, valid=valid,
                                   logprobs=lp))
        text = tok.decode([int(t) for t, v in zip(toks[0].tolist(), valid[0].tolist()) if v])
        ep.messages.append({"role": ASSISTANT, "content": text})
        ep.turns += 1
        ep.transcript.append(("assistant", text))

        call = parse_tool_call(text)
        if call is None:
            ep.final = text                      # not a tool call => final answer
            return ep
        name, args = call
        out, ok = toolbox.dispatch(name, args)
        ep.tool_calls += 1
        ep.tool_errors += 0 if ok else 1
        ep.messages.append({"role": TOOL, "content": out})
        ep.transcript.append(("tool", out))

    # Ran out of turns while still calling tools. The last assistant message is
    # then a tool call, from which extract_code recovers nothing -- so scoring it
    # gives a flat 0 for EVERY such episode, which is exactly what made the first
    # tool-using agentic run produce 100 identical zero rewards and no updates.
    # The code the agent last submitted to run_tests IS its working answer, so
    # fall back to that and keep the reward informative rather than constant.
    ep.final = ep.messages[-2]["content"] if len(ep.messages) >= 2 else ""
    if not _has_code(ep.final):
        for msg in reversed(ep.messages):
            if msg["role"] != ASSISTANT:
                continue
            call = parse_tool_call(msg["content"])
            if call and isinstance(call[1].get("code"), str) and call[1]["code"].strip():
                ep.final = "```python\n" + call[1]["code"] + "\n```"
                ep.final_from_tool_call = True
                break
    return ep


def episode_reward(ep: Episode, tests: list[str], timeout: float = 6.0,
                   setup: str = "") -> tuple[float, str]:
    """Reward the FINAL answer's code against the hidden tests.

    Only the final answer counts. Rewarding intermediate tool successes sounds
    helpful and is a reward-hacking surface: the cheapest way to farm per-turn
    credit is to call a trivially-passing tool repeatedly and never answer.
    """
    from nanocoder.reward import code_reward
    return code_reward(ep.final, tests, timeout=timeout, setup=setup)
